// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGG7RJZp1q1cNqsAQtbEyh8IN1Jzidu7k',
    appId: '1:54334030504:web:4c7df7fbc633643de1b89d',
    messagingSenderId: '54334030504',
    projectId: 'flutterauth-75cd9',
    authDomain: 'flutterauth-75cd9.firebaseapp.com',
    storageBucket: 'flutterauth-75cd9.firebasestorage.app',
    measurementId: 'G-R90FZCQD0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR-YkzW8TqDeak62l-dpFxZX6mrfgZH7k',
    appId: '1:54334030504:android:bb452d74a84d3c78e1b89d',
    messagingSenderId: '54334030504',
    projectId: 'flutterauth-75cd9',
    storageBucket: 'flutterauth-75cd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFQaf9tpq2KniwZmXXuwpk72IiiuNtu0I',
    appId: '1:54334030504:ios:e0c42dcde6d2b9e6e1b89d',
    messagingSenderId: '54334030504',
    projectId: 'flutterauth-75cd9',
    storageBucket: 'flutterauth-75cd9.firebasestorage.app',
    iosBundleId: 'com.example.loginProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFQaf9tpq2KniwZmXXuwpk72IiiuNtu0I',
    appId: '1:54334030504:ios:e0c42dcde6d2b9e6e1b89d',
    messagingSenderId: '54334030504',
    projectId: 'flutterauth-75cd9',
    storageBucket: 'flutterauth-75cd9.firebasestorage.app',
    iosBundleId: 'com.example.loginProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGG7RJZp1q1cNqsAQtbEyh8IN1Jzidu7k',
    appId: '1:54334030504:web:f0e42119d53f4238e1b89d',
    messagingSenderId: '54334030504',
    projectId: 'flutterauth-75cd9',
    authDomain: 'flutterauth-75cd9.firebaseapp.com',
    storageBucket: 'flutterauth-75cd9.firebasestorage.app',
    measurementId: 'G-FB9SQ3S4M3',
  );
}
